In [1]:
import numpy as np

In [5]:
#create - from lists
arr = np.array([1,2,3,4,5])
print(arr, type(arr), arr.shape)

arr2 = np.array([1,2,3,4,5,"prime"])
print(arr2, type(arr2), arr2.shape)

arr2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D, arr2D.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> (5,)
['1' '2' '3' '4' '5' 'prime'] <class 'numpy.ndarray'> (6,)
[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)


In [16]:
#Create
arr1 = np.zeros((2,3), dtype="int64") #prefill
print(arr1,arr1.shape)

arr2 = np.ones((2,3), dtype="int64") #prefill
print(arr2, arr2.shape)

arr3 = np.full((3,4), 100) #prefill with val
print(arr3, arr3.shape)

arr4 = np.eye((3)) #idendity matrix
print(arr4, arr4.shape)

arr5 = np.arange(0,11,2) #range elements
print(arr5, arr5.shape)

arr6 = np.linspace(1,100,3) #evenly spaced arrays
print(arr6, arr6.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[[1 1 1]
 [1 1 1]] (2, 3)
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[ 0  2  4  6  8 10] (6,)
[  1.   50.5 100. ] (3,)


In [18]:
# Properties
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.ndim)

float_arr = arr.astype(np.float64)
print(float_arr, float_arr.dtype)

(3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


In [8]:
#Operations on arrays

arr = np.array([[1,2,3], [4,5,6]])
print(arr, arr.shape)

reshaped = arr.reshape((3,2))
print(reshaped, reshaped.shape)

flattened = arr.flatten() #20 => 10
print(flattened, flattened.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [11]:
#Indexing
#arr = np.array([1,2,3,4,5])
arr = np.array([[1,2,3], [4,5,6]])

print(arr[0][2])

3


In [12]:
#Fancy Indexing
arr = np.array([1,2,3,4,5])

idx = [0,1,3]
print(arr[idx])

[1 2 4]


In [13]:
#Boolean Indexing
arr = np.array([1,2,3,4,5])

print(arr[arr >3])

[4 5]


In [3]:
#Slicing indexing
arr= np.array([1,2,3,4,5])

print(arr[1:4])
print(arr[1:])
print(arr[:4])
print(arr[:])

[2 3 4]
[2 3 4 5]
[1 2 3 4]
[1 2 3 4 5]


In [5]:
#Copy vs View
nums = [1,2,3,4,5]
sub_list = nums[1:3]
print(sub_list)
sub_list[0] = 200

print(sub_list)
print(nums)

arr = np.array([1,2,3,4,5])

[2, 3]
[200, 3]
[1, 2, 3, 4, 5]


In [7]:
#Data types

arr = np.array([3 + 5j])
print(arr, arr.dtype)


[3.+5.j] complex128


In [12]:
# Multi-dimensional arrays

arr2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D)

print(np.sum(arr2D))

sum_of_columns = np.sum(arr2D, axis = 0)
print(sum_of_columns)

sum_of_rows = np.sum(arr2D, axis = 1)
print(sum_of_rows)

print(arr2D[0:2,1:2])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


In [13]:
#3D array
arr3D = np.array([[[1,2], [3,4],[5,6]],[[7,8],[9,10],[11,12]]]) #2 x 3 x 1

print(arr3D, arr3D.shape)

#indexing
print(arr3D[1,1,0])

#slicing
print(arr3D[:,0,:]) #first row from both layers

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
9
[[1 2]
 [7 8]]


In [16]:
#Vectorization

arr = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

print(arr ** 2)
print(arr + 10)
print(arr + arr2)

[ 1  4  9 16 25]
[11 12 13 14 15]
[ 7  9 11 13 15]
